const express=require('express');const http=require('http');const path=require('path');const fs=require('fs');const crypto=require('crypto');const bcrypt=require('bcryptjs');const Database=require('better-sqlite3');const multer=require('multer');const {WebSocketServer}=require('ws');
const app=express(),server=http.createServer(app),PORT=process.env.PORT||3000;
const DATA=process.env.DATA_DIR||path.join(__dirname,'data');const AUDIO=path.join(DATA,'audio');fs.mkdirSync(AUDIO,{recursive:true});
const db=new Database(path.join(DATA,'warehouse.db'));db.pragma('journal_mode=WAL');
const now=()=>new Date().toISOString(), token=()=>crypto.randomBytes(24).toString('hex'), up=v=>(v??'').toString().trim().toUpperCase();const j=v=>{try{return JSON.parse(v)}catch{return null}};
const schema=`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,role TEXT NOT NULL,status TEXT DEFAULT 'available',password_hash TEXT,can_send INTEGER DEFAULT 1,can_receive INTEGER DEFAULT 1,can_customize INTEGER DEFAULT 0,permissions TEXT DEFAULT '{}',active INTEGER DEFAULT 1,default_page TEXT DEFAULT 'home',created_at TEXT NOT NULL,UNIQUE(name,role));
CREATE TABLE IF NOT EXISTS orders(id INTEGER PRIMARY KEY AUTOINCREMENT,kind TEXT DEFAULT 'normal',number TEXT,letter TEXT,size TEXT,color TEXT,notes TEXT,code TEXT,status TEXT DEFAULT 'new',priority TEXT DEFAULT 'normal',sender_id INTEGER,sender_name TEXT,claimant_id INTEGER,claimant_name TEXT,prepared_by TEXT,prepared_at TEXT,closed_reason TEXT,edit_lock INTEGER DEFAULT 0,edit_by TEXT,edit_started_at TEXT,check_result TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS order_events(id INTEGER PRIMARY KEY AUTOINCREMENT,order_id INTEGER,type TEXT,actor_id INTEGER,actor_name TEXT,details TEXT,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS order_audio(id INTEGER PRIMARY KEY AUTOINCREMENT,order_id INTEGER,file_name TEXT,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS replies(id INTEGER PRIMARY KEY AUTOINCREMENT,order_id INTEGER,sender_id INTEGER,sender_name TEXT,type TEXT,text TEXT,audio_file TEXT,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS displays(id INTEGER PRIMARY KEY AUTOINCREMENT,order_id INTEGER,number TEXT,letter TEXT,size TEXT,color TEXT,status TEXT DEFAULT 'requested',exact_piece INTEGER DEFAULT 0,created_by TEXT,completed_by TEXT,ended_by TEXT,end_reason TEXT,ack_by TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS special_requests(id INTEGER PRIMARY KEY AUTOINCREMENT,sender_id INTEGER,sender_name TEXT,target_id INTEGER,target_name TEXT,type TEXT DEFAULT 'custom',text TEXT,status TEXT DEFAULT 'new',created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS summons(id INTEGER PRIMARY KEY AUTOINCREMENT,caller_id INTEGER,caller_name TEXT,target_id INTEGER,target_name TEXT,location TEXT,detail TEXT,response TEXT,status TEXT DEFAULT 'new',created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS notifications(id INTEGER PRIMARY KEY AUTOINCREMENT,sender_id INTEGER,sender_name TEXT,target_id INTEGER,target_name TEXT,text TEXT,type TEXT DEFAULT 'info',ack INTEGER DEFAULT 0,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS ui_config(key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS audit(id INTEGER PRIMARY KEY AUTOINCREMENT,actor_id INTEGER,actor_name TEXT,action TEXT,entity_type TEXT,entity_id INTEGER,details TEXT,created_at TEXT NOT NULL);`;
db.exec(schema);
try{db.exec("ALTER TABLE orders ADD COLUMN kind TEXT DEFAULT 'normal'")}catch{}
try{db.exec("ALTER TABLE users ADD COLUMN permissions TEXT DEFAULT '{}'")}catch{}
const defaults={supervisor_password:bcrypt.hashSync('123456',10),prep_limit:'10',unconfirmed_seconds:'30',audio_retention_days:'30',history_limit:'100',display_alert_seconds:'30',display_alert_enabled:'1',summon_locations:JSON.stringify(['كاشير','بلاستيكات','المكتب','الجسر','ورا اللوحة']),colors:JSON.stringify(['BLK','BRN','COF','GRY','KHA','NVY','CML','TAN','CRM','WHT','BLU','DGRY','LGRY','GRN','OLV']),letters:JSON.stringify(['R','S','B','Z']),sizes:JSON.stringify(['39','40','41','42','42.5','43','44','45','46','47','48','49','50'])};for(const[k,v]of Object.entries(defaults))db.prepare('INSERT OR IGNORE INTO settings VALUES(?,?)').run(k,v);
if(!db.prepare('SELECT 1 FROM users LIMIT 1').get()){const t=now(),q=db.prepare('INSERT INTO users(name,role,password_hash,can_customize,permissions,created_at) VALUES(?,?,?,?,?)');q.run('المشرف','supervisor',defaults.supervisor_password,1,t);q.run('موظف الصالة','downstairs',null,0,t);q.run('حافظ','upstairs',null,0,t);q.run('موظف مستودع 2','upstairs',null,0,t)}
const setting=k=>db.prepare('SELECT value FROM settings WHERE key=?').get(k)?.value;const set=(k,v)=>db.prepare('INSERT INTO settings VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').run(k,String(v));const audit=(u,a,t,id,d='')=>db.prepare('INSERT INTO audit(actor_id,actor_name,action,entity_type,entity_id,details,created_at) VALUES(?,?,?,?,?,?,?)').run(u?.id,nullish(u?.name),a,t,id,d,now());function nullish(v){return v??null}function event(id,type,u,d=''){db.prepare('INSERT INTO order_events(order_id,type,actor_id,actor_name,details,created_at) VALUES(?,?,?,?,?,?)').run(id,type,u?.id,nullish(u?.name),d,now());audit(u,type,'order',id,d)}
const sessions=new Map(),clients=new Set(),callPeers=new Map();function emit(type,p={}){const m=JSON.stringify({type,...p});for(const c of clients)if(c.readyState===1)c.send(m)}
function auth(req,res,next){const t=(req.headers.authorization||'').replace('Bearer ','');const u=sessions.get(t);if(!u)return res.status(401).json({error:'غير مسجل الدخول'});req.user=u;next()}function supervisor(u){return u.role==='supervisor'}function can(u,key){return supervisor(u)||u[key]}
app.use(express.json({limit:'3mb'}));app.use(express.urlencoded({extended:true}));app.use(express.static(path.join(__dirname,'public')));app.use('/audio',express.static(AUDIO));
const upload=multer({storage:multer.diskStorage({destination:AUDIO,filename:(r,f,cb)=>cb(null,Date.now()+'-'+token()+path.extname(f.originalname||'.webm'))}),limits:{fileSize:12*1024*1024}});
const orderBy=id=>db.prepare('SELECT * FROM orders WHERE id=?').get(id);const code=o=>[o.number,o.letter,o.size,o.color].filter(Boolean).join('-');const activeStatuses=['new','claimed','searching','needs_reply','prepared','waiting','unconfirmed','editing'];
app.get('/health',(q,r)=>r.json({ok:true,time:now(),db:'sqlite-wal'}));
app.post('/api/login',(req,res)=>{const r=req.body.role,n=(req.body.name||'').trim();if(r==='supervisor'){const u=db.prepare("SELECT * FROM users WHERE role='supervisor' AND name=? AND active=1").get(n||'المشرف');if(!u||!bcrypt.compareSync(req.body.password||'',u.password_hash))return res.status(401).json({error:'بيانات المشرف غير صحيحة'});const x={id:u.id,name:u.name,role:u.role};const t=token();sessions.set(t,x);audit(x,'login','user',u.id);return res.json({token:t,user:x})}if(!['downstairs','upstairs'].includes(r)||!n)return res.status(400).json({error:'اختر الدور واكتب الاسم'});let u=db.prepare('SELECT * FROM users WHERE name=? AND role=? AND active=1').get(n,r);if(!u){const i=db.prepare('INSERT INTO users(name,role,created_at) VALUES(?,?,?)').run(n,r,now());u={id:i.lastInsertRowid,name:n,role:r}}const x={id:u.id,name:u.name,role:u.role};const t=token();sessions.set(t,x);audit(x,'login','user',u.id);res.json({token:t,user:x})});
app.post('/api/logout',auth,(req,res)=>{const t=(req.headers.authorization||'').replace('Bearer ','');audit(req.user,'logout','user',req.user.id);sessions.delete(t);res.json({ok:true})});
app.get('/api/bootstrap',auth,(req,res)=>{const lim=Number(setting('history_limit')||100);const orders=db.prepare(`SELECT * FROM orders WHERE status NOT IN ('closed','cancelled','unconfirmed') OR edit_lock=1 ORDER BY datetime(created_at) ASC`).all();const history=db.prepare(`SELECT * FROM orders ORDER BY datetime(created_at) DESC LIMIT ?`).all(lim);const users=db.prepare('SELECT id,name,role,status,can_send,can_receive,can_customize,permissions,active,default_page FROM users ORDER BY role,name').all();const displays=db.prepare("SELECT * FROM displays WHERE status IN ('requested','waiting','displayed') ORDER BY datetime(created_at) ASC").all();const allDisplays=db.prepare('SELECT * FROM displays ORDER BY datetime(created_at) DESC LIMIT 300').all();const specials=db.prepare('SELECT * FROM special_requests ORDER BY datetime(created_at) DESC LIMIT 100').all();const summons=db.prepare('SELECT * FROM summons ORDER BY datetime(created_at) DESC LIMIT 100').all();const notes=db.prepare('SELECT * FROM notifications WHERE target_id IS NULL OR target_id=? ORDER BY datetime(created_at) DESC LIMIT 100').all(req.user.id);const events=db.prepare('SELECT * FROM audit ORDER BY datetime(created_at) DESC LIMIT 200').all();res.json({me:req.user,orders,history,users,displays,allDisplays,specials,summons,notifications:notes,audit:events,settings:{prepLimit:+setting('prep_limit'),unconfirmedSeconds:+setting('unconfirmed_seconds'),audioRetentionDays:+setting('audio_retention_days'),historyLimit:+setting('history_limit'),displayAlertSeconds:+setting('display_alert_seconds'),displayAlertEnabled:setting('display_alert_enabled')==='1',locations:j(setting('summon_locations')),colors:j(setting('colors')),letters:j(setting('letters')),sizes:j(setting('sizes'))},ui:{}})});
app.get('/api/order/:id/details',auth,(req,res)=>{const o=orderBy(req.params.id);if(!o)return res.status(404).json({error:'الطلب غير موجود'});res.json({order:o,events:db.prepare('SELECT * FROM order_events WHERE order_id=? ORDER BY id').all(o.id),replies:db.prepare('SELECT * FROM replies WHERE order_id=? ORDER BY id').all(o.id),audio:db.prepare('SELECT * FROM order_audio WHERE order_id=? ORDER BY id').all(o.id)})});
app.post('/api/orders',auth,(req,res)=>{if(req.user.role==='upstairs')return res.status(403).json({error:'هذه العملية للصالة'});const b=req.body,t=now(),number=up(b.number),letter=up(b.letter),size=up(b.size),color=up(b.color),notes=(b.notes||'').trim();if(!number&&!letter&&!size&&!color&&!notes)return res.status(400).json({error:'أدخل بيانات الطلب'});const similar=db.prepare("SELECT id,code FROM orders WHERE status NOT IN ('closed','cancelled') AND COALESCE(code,'')=? ORDER BY id DESC LIMIT 1").get([number,letter,size,color].filter(Boolean).join('-'));if(similar&&b.allowDuplicate!==true)return res.status(409).json({error:'يوجد طلب مشابه بالفعل',duplicateId:similar.id});const info=db.prepare('INSERT INTO orders(kind,number,letter,size,color,notes,code,status,priority,sender_id,sender_name,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(b.kind||'normal',number,letter,size,color,notes,code({number,letter,size,color}),'new',b.priority==='urgent'?'urgent':'normal',req.user.id,req.user.name,t,t);event(info.lastInsertRowid,'created',req.user,notes);emit('orders_changed',{orderId:info.lastInsertRowid});res.json({ok:true,id:info.lastInsertRowid})});
app.post('/api/orders/:id/claim',auth,(req,res)=>{const o=orderBy(req.params.id);if(!o)return res.status(404).json({error:'الطلب غير موجود'});if(req.user.role==='downstairs')return res.status(403).json({error:'المستودع يستلم الطلب'});if(o.claimant_id)return res.status(409).json({error:`تم استلامه بواسطة ${o.claimant_name}`});const n=db.prepare("SELECT COUNT(*) c FROM orders WHERE status IN ('claimed','searching','needs_reply')").get().c;if(n>=Number(setting('prep_limit')||10))return res.status(409).json({error:`الحد الحالي ${setting('prep_limit')}`});db.prepare("UPDATE orders SET status='claimed',claimant_id=?,claimant_name=?,updated_at=? WHERE id=? AND claimant_id IS NULL").run(req.user.id,req.user.name,now(),o.id);event(o.id,'claimed',req.user);emit('orders_changed',{orderId:o.id});res.json({ok:true})});
app.post('/api/orders/:id/status',auth,(req,res)=>{const o=orderBy(req.params.id),s=req.body.status;if(!o)return res.status(404).json({error:'الطلب غير موجود'});const allowed=['new','claimed','searching','needs_reply','prepared','waiting','unconfirmed','closed','cancelled','returned'];if(!allowed.includes(s))return res.status(400).json({error:'الحالة غير صحيحة'});if(s==='prepared'&&req.user.role==='downstairs')return res.status(403).json({error:'التجهيز للمستودع'});if(s==='closed'&&req.user.role==='upstairs')return res.status(403).json({error:'الإغلاق النهائي من الصالة'});const vals=[s,now()];let sql='UPDATE orders SET status=?,updated_at=?';if(s==='prepared')sql+=',prepared_by=?,prepared_at=?',vals.push(req.user.name,now());if(s==='closed'||s==='returned'||s==='cancelled')sql+=',closed_reason=?',vals.push(req.body.reason||s);sql+=' WHERE id=?';vals.push(o.id);db.prepare(sql).run(...vals);event(o.id,s,req.user,req.body.details||req.body.reason||'');emit('orders_changed',{orderId:o.id});res.json({ok:true})});
app.post('/api/orders/:id/reopen',auth,(req,res)=>{const o=orderBy(req.params.id);if(!o)return res.status(404).json({error:'الطلب غير موجود'});db.prepare("UPDATE orders SET status='new',claimant_id=NULL,claimant_name=NULL,closed_reason=NULL,updated_at=? WHERE id=?").run(now(),o.id);event(o.id,'reopened',req.user,req.body.reason||'');emit('orders_changed',{orderId:o.id});res.json({ok:true})});
app.post('/api/orders/:id/edit/start',auth,(req,res)=>{const o=orderBy(req.params.id);if(!o)return res.status(404).json({error:'الطلب غير موجود'});if(o.edit_lock&&o.edit_by!==req.user.name)return res.status(409).json({error:`الطلب قيد التعديل بواسطة ${o.edit_by}`});db.prepare("UPDATE orders SET edit_lock=1,edit_by=?,edit_started_at=?,status='editing',updated_at=? WHERE id=?").run(req.user.name,now(),now(),o.id);event(o.id,'edit_started',req.user);emit('orders_changed',{orderId:o.id});res.json({ok:true,order:o})});
app.post('/api/orders/:id/edit',auth,(req,res)=>{const o=orderBy(req.params.id);if(!o)return res.status(404).json({error:'الطلب غير موجود'});const b=req.body,n=up(b.number),l=up(b.letter),s=up(b.size),c=up(b.color);const newCode=[n,l,s,c].filter(Boolean).join('-');db.prepare("UPDATE orders SET number=?,letter=?,size=?,color=?,notes=?,code=?,edit_lock=0,edit_by=NULL,edit_started_at=NULL,status='new',claimant_id=NULL,claimant_name=NULL,updated_at=? WHERE id=?").run(n,l,s,c,(b.notes||'').trim(),newCode,now(),o.id);event(o.id,'edited',req.user,JSON.stringify({before:{number:o.number,letter:o.letter,size:o.size,color:o.color},after:{number:n,letter:l,size:s,color:c}}));emit('orders_changed',{orderId:o.id});res.json({ok:true})});
app.post('/api/orders/:id/check',auth,(req,res)=>{const o=orderBy(req.params.id);if(!o)return res.status(404).json({error:'الطلب غير موجود'});event(o.id,'check_requested',req.user);db.prepare("UPDATE orders SET status='waiting',updated_at=? WHERE id=? AND status NOT IN ('closed','cancelled')").run(now(),o.id);emit('orders_changed',{orderId:o.id});res.json({ok:true})});
app.post('/api/orders/:id/check-result',auth,(req,res)=>{const o=orderBy(req.params.id);if(!o)return res.status(404).json({error:'الطلب غير موجود'});const r=req.body.result;if(!['موجود','غير موجود','يوجد بديل'].includes(r))return res.status(400).json({error:'نتيجة غير صحيحة'});db.prepare('UPDATE orders SET check_result=?,status=?,updated_at=? WHERE id=?').run(r,'waiting',now(),o.id);event(o.id,'check_result',req.user,r);emit('orders_changed',{orderId:o.id});res.json({ok:true})});
app.post('/api/orders/:id/alternative',auth,(req,res)=>{const o=orderBy(req.params.id);if(!o)return res.status(404).json({error:'الطلب غير موجود'});event(o.id,'alternative',req.user,req.body.text||'يوجد بديل');db.prepare("UPDATE orders SET status='needs_reply',updated_at=? WHERE id=?").run(now(),o.id);db.prepare('INSERT INTO notifications(sender_id,sender_name,target_id,target_name,text,type,created_at) VALUES(?,?,?,?,?,?,?)').run(req.user.id,req.user.name,o.sender_id,o.sender_name,req.body.text||'يوجد بديل للطلب','alternative',now());emit('notifications_changed',{});emit('orders_changed',{orderId:o.id});res.json({ok:true})});
app.post('/api/orders/:id/transfer',auth,(req,res)=>{const o=orderBy(req.params.id),u=db.prepare("SELECT * FROM users WHERE id=? AND role='upstairs' AND active=1").get(Number(req.body.toId));if(!o||!u)return res.status(400).json({error:'الطلب أو الموظف غير موجود'});db.prepare("UPDATE orders SET claimant_id=?,claimant_name=?,status='claimed',updated_at=? WHERE id=?").run(u.id,u.name,now(),o.id);event(o.id,'transfer',req.user,`إلى ${u.name}`);emit('orders_changed',{orderId:o.id});res.json({ok:true})});
app.post('/api/orders/:id/reply',auth,(req,res)=>{const o=orderBy(req.params.id),text=(req.body.text||'').trim();if(!o||!text)return res.status(400).json({error:'البيانات ناقصة'});db.prepare('INSERT INTO replies(order_id,sender_id,sender_name,type,text,created_at) VALUES(?,?,?,?,?,?)').run(o.id,req.user.id,req.user.name,'text',text,now());event(o.id,'reply',req.user,text);db.prepare("UPDATE orders SET status='needs_reply',updated_at=? WHERE id=?").run(now(),o.id);emit('orders_changed',{orderId:o.id});res.json({ok:true})});
app.post('/api/orders/:id/audio',auth,upload.single('audio'),(req,res)=>{const o=orderBy(req.params.id);if(!o||!req.file)return res.status(400).json({error:'الصوت غير موجود'});db.prepare('INSERT INTO order_audio(order_id,file_name,created_at) VALUES(?,?,?)').run(o.id,req.file.filename,now());event(o.id,'audio',req.user);emit('orders_changed',{orderId:o.id});res.json({ok:true,file:req.file.filename})});
app.post('/api/special',auth,(req,res)=>{const target=req.body.targetId?db.prepare('SELECT * FROM users WHERE id=?').get(req.body.targetId):null;const text=(req.body.text||'').trim();if(!text)return res.status(400).json({error:'اكتب الطلب الخاص'});const i=db.prepare('INSERT INTO special_requests(sender_id,sender_name,target_id,target_name,type,text,created_at) VALUES(?,?,?,?,?,?,?)').run(req.user.id,req.user.name,target?.id||null,target?.name||null,req.body.type||'custom',text,now());audit(req.user,'special_request','special',i.lastInsertRowid,text);emit('special_changed',{});res.json({ok:true})});
app.post('/api/summons',auth,(req,res)=>{const target=db.prepare('SELECT * FROM users WHERE id=? AND active=1').get(Number(req.body.targetId));if(!target)return res.status(400).json({error:'اختر موظفًا'});const i=db.prepare('INSERT INTO summons(caller_id,caller_name,target_id,target_name,location,detail,created_at) VALUES(?,?,?,?,?,?,?)').run(req.user.id,req.user.name,target.id,target.name,req.body.location||'غير محدد',(req.body.detail||'').trim(),now());audit(req.user,'summon','summon',i.lastInsertRowid,target.name);emit('summons_changed',{});res.json({ok:true})});
app.post('/api/summons/:id/respond',auth,(req,res)=>{db.prepare("UPDATE summons SET response=?,status='answered' WHERE id=? AND target_id=?").run(req.body.response||'حاضر',req.params.id,req.user.id);emit('summons_changed',{});res.json({ok:true})});
app.post('/api/notifications',auth,(req,res)=>{const text=(req.body.text||'').trim();if(!text)return res.status(400).json({error:'اكتب التنبيه'});const targets=Array.isArray(req.body.targetIds)?req.body.targetIds:[];if(targets.length===0){db.prepare('INSERT INTO notifications(sender_id,sender_name,text,type,created_at) VALUES(?,?,?,?,?)').run(req.user.id,req.user.name,text,req.body.type||'info',now())}else{const ins=db.prepare('INSERT INTO notifications(sender_id,sender_name,target_id,target_name,text,type,created_at) VALUES(?,?,?,?,?,?,?)');for(const id of targets){const u=db.prepare('SELECT name FROM users WHERE id=?').get(id);if(u)ins.run(req.user.id,req.user.name,id,u.name,text,req.body.type||'info',now())}}audit(req.user,'notification','notification',null,text);emit('notifications_changed',{});res.json({ok:true})});
app.post('/api/notifications/:id/ack',auth,(req,res)=>{db.prepare('UPDATE notifications SET ack=1 WHERE id=? AND (target_id IS NULL OR target_id=?)').run(req.params.id,req.user.id);res.json({ok:true})});
app.post('/api/users',auth,(req,res)=>{if(!supervisor(req.user))return res.status(403).json({error:'للمشرف فقط'});const n=(req.body.name||'').trim(),r=req.body.role;if(!n||!['supervisor','downstairs','upstairs'].includes(r))return res.status(400).json({error:'بيانات الموظف ناقصة'});try{const i=db.prepare('INSERT INTO users(name,role,password_hash,can_customize,permissions,created_at) VALUES(?,?,?,?,?)').run(n,r,r==='supervisor'?setting('supervisor_password'):null,req.body.canCustomize?1:0,now());audit(req.user,'user_created','user',i.lastInsertRowid,n);emit('users_changed',{});res.json({ok:true,id:i.lastInsertRowid})}catch(e){res.status(409).json({error:'المستخدم موجود'})}});
app.post('/api/users/:id/permissions',auth,(req,res)=>{if(!supervisor(req.user))return res.status(403).json({error:'للمشرف فقط'});db.prepare('UPDATE users SET can_send=?,can_receive=?,can_customize=?,permissions=?,default_page=? WHERE id=?').run(req.body.canSend?1:0,req.body.canReceive?1:0,req.body.canCustomize?1:0,JSON.stringify(req.body.permissions||{}),req.body.defaultPage||'home',req.params.id);audit(req.user,'permissions_changed','user',req.params.id,JSON.stringify(req.body));emit('users_changed',{});res.json({ok:true})});
app.post('/api/users/:id/status',auth,(req,res)=>{if(!supervisor(req.user)&&Number(req.params.id)!==req.user.id)return res.status(403).json({error:'غير مسموح'});db.prepare('UPDATE users SET status=? WHERE id=?').run(req.body.status,req.params.id);audit(req.user,'status_changed','user',req.params.id,req.body.status);emit('users_changed',{});res.json({ok:true})});
app.post('/api/settings',auth,(req,res)=>{if(!supervisor(req.user))return res.status(403).json({error:'للمشرف فقط'});for(const k of ['prep_limit','unconfirmed_seconds','audio_retention_days','history_limit','display_alert_seconds','display_alert_enabled','summon_locations','colors','letters','sizes'])if(req.body[k]!==undefined)set(k,typeof req.body[k]==='object'?JSON.stringify(req.body[k]):req.body[k]);audit(req.user,'settings_changed','settings',null,JSON.stringify(req.body));emit('settings_changed',{});res.json({ok:true})});
app.post('/api/password',auth,(req,res)=>{if(!supervisor(req.user))return res.status(403).json({error:'للمشرف فقط'});if((req.body.password||'').length<6)return res.status(400).json({error:'كلمة المرور 6 أحرف على الأقل'});set('supervisor_password',bcrypt.hashSync(req.body.password,10));db.prepare("UPDATE users SET password_hash=? WHERE role='supervisor' AND id=?").run(setting('supervisor_password'),req.user.id);audit(req.user,'password_changed','user',req.user.id);emit('password_changed',{});res.json({ok:true})});
app.get('/api/history',auth,(req,res)=>{const q=up(req.query.q||''),from=req.query.from||'',to=req.query.to||'',status=req.query.status||'';let sql='SELECT * FROM orders WHERE 1=1',a=[];if(q){sql+=' AND (UPPER(COALESCE(code,"")) LIKE ? OR UPPER(COALESCE(sender_name,"")) LIKE ? OR UPPER(COALESCE(claimant_name,"")) LIKE ?)';const x='%'+q+'%';a.push(x,x,x)}if(from){sql+=' AND date(created_at)>=date(?)';a.push(from)}if(to){sql+=' AND date(created_at)<=date(?)';a.push(to)}if(status){sql+=' AND status=?';a.push(status)}sql+=' ORDER BY datetime(created_at) DESC LIMIT 500';res.json({orders:db.prepare(sql).all(...a)})});
app.delete('/api/history',auth,(req,res)=>{if(!supervisor(req.user))return res.status(403).json({error:'للمشرف فقط'});audit(req.user,'history_deleted','history',null,'deleted orders/events');db.prepare("DELETE FROM order_events WHERE order_id IN (SELECT id FROM orders WHERE status IN ('closed','cancelled'))").run();db.prepare("DELETE FROM orders WHERE status IN ('closed','cancelled')").run();res.json({ok:true})});
app.post('/api/displays',auth,(req,res)=>{const b=req.body,src=b.orderId?orderBy(b.orderId):null,n=up(b.number||src?.number),l=up(b.letter||src?.letter),s=up(b.size||src?.size),c=up(b.color||src?.color);if(!n&&!l&&!s&&!c)return res.status(400).json({error:'بيانات العرض ناقصة'});const dup=db.prepare("SELECT * FROM displays WHERE status IN ('requested','waiting','displayed') AND number=? AND letter=? AND size=? AND color=?").get(n,l,s,c);if(dup)return res.status(409).json({error:`الموظف ${dup.created_by} أضاف العرض بالفعل`});const i=db.prepare('INSERT INTO displays(order_id,number,letter,size,color,status,exact_piece,created_by,created_at,updated_at) VALUES(?,?,?,?,? ,"requested",?,?,?,?)').run(b.orderId||null,n,l,s,c,b.exactPiece?1:0,req.user.name,now(),now());if(src)event(src.id,'display_requested',req.user,`${n}-${l}-${s}-${c}`);emit('displays_changed',{});res.json({ok:true,id:i.lastInsertRowid})});
app.post('/api/displays/:id/status',auth,(req,res)=>{const d=db.prepare('SELECT * FROM displays WHERE id=?').get(req.params.id),s=req.body.status;if(!d)return res.status(404).json({error:'العرض غير موجود'});if(!['requested','waiting','displayed','ended','cancelled','expired'].includes(s))return res.status(400).json({error:'الحالة غير صحيحة'});db.prepare('UPDATE displays SET status=?,completed_by=?,ended_by=?,end_reason=?,updated_at=? WHERE id=?').run(s,s==='displayed'?req.user.name:d.completed_by,s==='ended'||s==='expired'?req.user.name:d.ended_by,req.body.reason||null,now(),d.id);emit('displays_changed',{});res.json({ok:true})});
app.post('/api/displays/:id/ack',auth,(req,res)=>{db.prepare('UPDATE displays SET ack_by=?,updated_at=? WHERE id=?').run(req.user.name,now(),req.params.id);emit('displays_changed',{});res.json({ok:true})});
app.post('/api/search',auth,(req,res)=>{const q=up(req.body.q||'');const x='%'+q+'%';res.json({orders:db.prepare('SELECT * FROM orders WHERE UPPER(COALESCE(code,"")) LIKE ? OR UPPER(COALESCE(sender_name,"")) LIKE ? OR UPPER(COALESCE(claimant_name,"")) LIKE ? ORDER BY datetime(created_at) DESC LIMIT 200').all(x,x,x),displays:db.prepare('SELECT * FROM displays WHERE UPPER(COALESCE(number||"-"||letter||"-"||size||"-"||color,"")) LIKE ? ORDER BY datetime(created_at) DESC LIMIT 100').all(x)})});
app.post('/api/ui',auth,(req,res)=>{if(!supervisor(req.user)&&!req.user.can_customize)return res.status(403).json({error:'لا تملك صلاحية التخصيص'});const scope=supervisor(req.user)?'global':`user:${req.user.id}`;set('ui:'+scope,JSON.stringify(req.body));audit(req.user,'ui_changed','ui',null,scope);res.json({ok:true})});
app.post('/api/cleanup',auth,(req,res)=>{if(!supervisor(req.user))return res.status(403).json({error:'للمشرف فقط'});const days=Number(setting('audio_retention_days')||30),cut=Date.now()-days*86400000;const rows=db.prepare('SELECT * FROM order_audio').all();for(const r of rows){if(new Date(r.created_at).getTime()<cut){try{fs.unlinkSync(path.join(AUDIO,r.file_name))}catch{}db.prepare('DELETE FROM order_audio WHERE id=?').run(r.id)}}res.json({ok:true})});
const wss=new WebSocketServer({server,path:'/ws'});wss.on('connection',(ws)=>{clients.add(ws);ws.isAlive=true;ws.on('pong',()=>ws.isAlive=true);ws.on('message',raw=>{const m=j(raw.toString());if(!m)return;if(m.type==='identify'){ws.userId=m.userId;callPeers.set(m.userId,ws)}else if(['call','answer','ice','hangup'].includes(m.type)){const target=callPeers.get(m.to);if(target?.readyState===1)target.send(JSON.stringify({...m,from:ws.userId}))}});ws.on('close',()=>{clients.delete(ws);if(ws.userId&&callPeers.get(ws.userId)===ws)callPeers.delete(ws.userId)});});setInterval(()=>{wss.clients.forEach(ws=>{if(ws.isAlive===false)return ws.terminate();ws.isAlive=false;ws.ping()})},30000);
setInterval(()=>{const sec=Number(setting('unconfirmed_seconds')||30);db.prepare("UPDATE orders SET status='unconfirmed',updated_at=? WHERE status='prepared' AND (julianday('now')-julianday(updated_at))*86400>=?").run(now(),sec);},5000);
setInterval(()=>{const sec=Number(setting('display_alert_seconds')||30);if(setting('display_alert_enabled')!=='1')return;const rows=db.prepare("SELECT * FROM displays WHERE status='requested'").all();for(const d of rows){if((Date.now()-new Date(d.created_at).getTime())/1000>=sec){db.prepare("UPDATE displays SET status='waiting',updated_at=? WHERE id=? AND status='requested'").run(now(),d.id);emit('display_alert',{displayId:d.id})}}},5000);
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));server.listen(PORT,()=>console.log(`Warehouse Orders listening on ${PORT}`));
